version: "3.9"
services:
  mydb:
    image: mysql:latest
    container_name: testdbpizzadelivery
    environment:
      - ACCEPT_EULA=Y
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysqlstorage:/var/lib/mysql
    #    - ./dao/src/scripts:/docker-entrypoint-initdb.d
    ports:
      - "3308:3308"
    restart: "unless-stopped"
  serverexample:
    container_name: myserver
    build:
      context: .
      dockerfile: Dockerfile
    image: serverexample
    depends_on:
      - mydb
    volumes:
      - ./core/target/web:/app/web
    ports:
      - "5050:5050"
    restart: "no"